### ISSUE TITLE
About node_modules folder

### ISSUE THREAD

**Issue by DavideViolante** [plm9606/automerge_actions#8]
First of all, thanks for this action.

About the latest commits, I think the node_modules folder should be included in any Github Actions, or, if not, use a bundler like [ncc](https://github.com/zeit/ncc) to build the action.

[In the documentation there is](https://help.github.com/en/actions/building-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github
) written to commit node_modules:

> From your terminal, commit your action.yml, index.js, node_modules, package.json, package-lock.json [...]

After that there is also the suggestion about not committing node_modules:

> As an alternative to checking in your node_modules directory you can use a tool called zeit/ncc to compile your code and modules into one file used for distribution.

I used ncc in [this action](https://github.com/DavideViolante/sprint-milestone-action/tree/v2.1.0) if you want to take a look.

I'm not sure your action is going to work now.

**Comment by plm9606** [comment]
It was my mistake. Added it now!
